name: Deploy to OVHCloud

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Images
        run: |
          docker-compose build

      - name: Deploy to OVHCloud
        run: |
          ssh -i ${{ secrets.OVH_SSH_KEY }} ${{ secrets.OVH_USER }}@${{ secrets.OVH_IP }} "
          cd /path/to/app && docker-compose down && docker-compose up -d"
