name: CI/CD to OVHcloud

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build and push Docker images
    - name: Build and Push Backend Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/backend

    - name: Build and Push Frontend Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend


    # Step 5: Deploy to OVHcloud
    - name: Deploy to OVHcloud
      run: |
        ssh -i ${{ secrets.OVH_SSH_KEY }} -o StrictHostKeyChecking=no ${{ secrets.OVH_USER }}@${{ secrets.OVH_IP }} << 'EOF'
          set -e

          
          cd /var/www/two-tier-app

          # Pull the latest images
          docker pull ${{ secrets.DOCKER_USERNAME }}/backend
          docker pull ${{ secrets.DOCKER_USERNAME }}/frontend

          # Update and restart the application
          docker-compose down
          docker-compose up -d
        EOF
